### ISSUE TITLE
Fix @font-face setup by adding ProximaNovaBold as ProximaNova font-weight: 700

### ISSUE THREAD

**Issue by wmcb91** [rideRTD/rtd-style#79]
In [_fontface.scss](/rideRTD/rtd-style/blob/master/scss/base/_fontface.scss) add the following on line 10

```scss
@font-face {
  font-family: 'ProximaNova';
  src: local('?'),
  url([COPY_DATA_FROM_PROXIMANOVABOLD])
      format('truetype');
  font-weight: bold;
  font-style: normal;
}
```
